CC=gcc
APP=chiller
PRJDIR=/mnt/hgfs/ShareDirHost/logical_control
OUTDIR=/mnt/hgfs/ShareDirHost/logical_control/bin

INCLUDE= \
	-I${PRJDIR}/src/${APP} \
	-I${PRJDIR}/src/${APP}/chillerpid \
	-I${PRJDIR}/src/signal \
	-I${PRJDIR}/src/es_print \
	-I${PRJDIR}/src/pid \
	-I${PRJDIR}/src/list \
	-I${PRJDIR}/src

LIB=-lpthread -lmosquitto -ljson-c

EXE=bbbb